version: '3.3'

services:
  db:
    container_name: giveaway_mysql
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: giveaway_wp
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
    container_name: giveaway_wp
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: giveaway_wp
      WORDPRESS_DEBUG: 1
    volumes:
      - "./.local/public/wp-content/plugins:/var/www/html/wp-content/plugins"
      - "./.local/public/wp-content/uploads:/var/www/html/wp-content/uploads"
      - "./.local/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
      - ".:/var/www/html/wp-content/themes/giveaway"
volumes:
  db_data: {}